- name: generate SSH key {{ ssh_key_filename }}
  user:
    name: "{{ ansible_user }}"
    generate_ssh_key: yes
    ssh_key_type: rsa
    ssh_key_bits: 4096
    ssh_key_file: .ssh/{{ ssh_key_filename }}
    ssh_key_passphrase: "{{ ssh_passphrase }}"
    force: no
  become: false

- name: generate SSH config file
  template:
    src: config
    dest: /home/{{ ansible_user }}/.ssh/config
  become: false