- name: Install Python {{ python_version }} and pipenv Homebrew packages
  community.general.homebrew:
    name: "{{ item }}"
  loop:
    - python@{{ python_version }}
    - pipenv
  when: ansible_distribution == 'MacOSX' or ansible_distribution == 'Ubuntu'