- name: Install git
  apt:
    name: git
    state: present
    update_cache: true
  become: true

- name: Set user.name
  git_config:
    name: user.name
    value: "{{ user_name }}"
    scope: global
  become: false

- name: Set user.email
  git_config:
    name: user.email
    value: "{{ user_email }}"
    scope: global
  become: false