- name: Install zsh shell
  community.general.homebrew:
    name: zsh
  when: ansible_distribution == 'Ubuntu'

- name: Capture zsh install location
  ansible.builtin.shell: which zsh
  register: which_zsh
  when: ansible_distribution == 'Ubuntu'

- name: Add zsh install to valid list of login shells
  ansible.builtin.shell: add-shell {{ which_zsh.stdout }}
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: Set zsh as default shell for {{ ansible_user_id }} in /etc/passwd
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: "{{ which_zsh.stdout }}"
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: Add Homebrew to PATH for zsh shell
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.zprofile"
    line: eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
    create: true
  when: ansible_distribution == 'Ubuntu'

- name: Make homebrew available to zsh shell too
  ansible.builtin.shell: eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
  become: true
  when: ansible_distribution == 'Ubuntu'
