- name: (Ubuntu) Install IntelliJ IDEA Ultimate as snap package
  community.general.snap:
    name: intellij-idea-ultimate
    classic: true
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: (MacOSX) Install IntelliJ IDEA Ultimate as Homebrew cask
  community.general.homebrew_cask:
    name: intellij-idea
  when: ansible_distribution == 'MacOSX'