- name: install goimports utility - {{ latest_version }}
  command: 
    cmd: /usr/local/go/bin/go install golang.org/x/tools/cmd/goimports@{{ latest_version }}
    creates: /home/{{ ansible_user }}/go/bin/goimports
  become: false

- name: install golint utility - {{ latest_version }}
  command:
    cmd: /usr/local/go/bin/go install golang.org/x/lint/golint@{{ latest_version }}
    creates: /home/{{ ansible_user }}/go/bin/golint
  become: false

- name: install golangci-lint utility - {{ golangci_lint_version }}
  ansible.builtin.debug:
    msg: TODO - install golangci-lint utility when useful
  become: false

- name: install gopls language server for IDEs - {{ latest_version }}
  command:
    cmd: /usr/local/go/bin/go install golang.org/x/tools/gopls@{{ latest_version }}
    creates: /home/{{ ansible_user }}/go/bin/gopls
  become: false

- name: install delve debugger utility - {{ latest_version }}
  command:
    cmd: /usr/local/go/bin/go install github.com/go-delve/delve/cmd/dlv@{{ latest_version }}
    creates: /home/{{ ansible_user }}/go/bin/dlv
  become: false

- name: install go-outline utility - {{ latest_version }}
  command:
    cmd: /usr/local/go/bin/go install github.com/ramya-rao-a/go-outline@{{ latest_version }}
    creates: /home/{{ ansible_user }}/go/bin/go-outline
  become: false

- name: install staticcheck utility - {{ latest_version }}
  command:
    cmd: /usr/local/go/bin/go install honnef.co/go/tools/cmd/staticcheck@{{ latest_version }}
    creates: /home/{{ ansible_user }}/go/bin/staticcheck
  become: false