- name: install goimports utility - {{ latest_version }}
  command: 
    cmd: /usr/local/go/bin/go install golang.org/x/tools/cmd/goimports@{{ latest_version }}
    creates: /home/{{ ansible_user }}/go/bin/goimports
  become: false

- name: install golint utility - {{ latest_version }}
  command:
    cmd: /usr/local/go/bin/go install golang.org/x/lint/golint@{{ latest_version }}
    creates: /home/{{ ansible_user }}/go/bin/golint
  become: false

- name: install golangci-lint utility - {{ golangci_lint_version }}
  ansible.builtin.debug:
    msg: TODO - install golangci-lint utility when useful
  become: false

- name: Download the golangci-lint install script
  get_url: 
    url: https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh 
    dest: /tmp
    mode: u+rwx
  become: false

- name: install golangci-lint utility - {{ golangci_lint_version }}
  command:
    cmd: /tmp/install.sh -b /home/{{ ansible_user }}/go/bin {{ golangci_lint_version }}
    creates: /home/{{ ansible_user }}/go/bin/golangci-lint
  become: false

- name: Delete the golangci-lint utility install script
  file:
    path: /tmp/install.sh
    state: absent
  become: false

- name: install gopls language server for IDEs - {{ latest_version }}
  command:
    cmd: /usr/local/go/bin/go install golang.org/x/tools/gopls@{{ latest_version }}
    creates: /home/{{ ansible_user }}/go/bin/gopls
  become: false

- name: install delve debugger utility - {{ latest_version }}
  command:
    cmd: /usr/local/go/bin/go install github.com/go-delve/delve/cmd/dlv@{{ latest_version }}
    creates: /home/{{ ansible_user }}/go/bin/dlv
  become: false

- name: install go-outline utility - {{ latest_version }}
  command:
    cmd: /usr/local/go/bin/go install github.com/ramya-rao-a/go-outline@{{ latest_version }}
    creates: /home/{{ ansible_user }}/go/bin/go-outline
  become: false

- name: install staticcheck utility - {{ latest_version }}
  command:
    cmd: /usr/local/go/bin/go install honnef.co/go/tools/cmd/staticcheck@{{ latest_version }}
    creates: /home/{{ ansible_user }}/go/bin/staticcheck
  become: false

- name: install gotests utility - {{ latest_version }}
  command:
    cmd: /usr/local/go/bin/go install github.com/cweill/gotests/gotests@{{ latest_version }}
    creates: /home/{{ ansible_user }}/go/bin/gotests
  become: false

- name: install shadow linting utility - {{ latest_version }}
  command:
    cmd: /usr/local/go/bin/go install golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow@{{ latest_version }}
    creates: /home/{{ ansible_user }}/go/bin/shadow
  become: false

- name: install godoc utility - {{ latest_version }}
  command:
    cmd: /usr/local/go/bin/go install golang.org/x/tools/cmd/godoc@{{ latest_version }}
    creates: /home/{{ ansible_user }}/go/bin/godoc
  become: false

- name: install godoctor utility - {{ latest_version }}
  command:
    cmd: /usr/local/go/bin/go install github.com/godoctor/godoctor@{{ latest_version }}
    creates: /home/{{ ansible_user }}/go/bin/godoctor
  become: false

- name: install errcheck linter utility - {{ latest_version }}
  command:
    cmd: /usr/local/go/bin/go install github.com/kisielk/errcheck@{{ latest_version }}
    creates: /home/{{ ansible_user }}/go/bin/errcheck
  become: false