- name: Install Golang utilities Homebrew packages
  community.general.homebrew:
    name: "{{ item }}"
  loop:
    - golangci-lint
    - sqlc
  when: ansible_distribution == 'MacOSX' or ansible_distribution == 'Ubuntu'
