- name: Install Golang {{ go_version }} Homebrew package
  community.general.homebrew:
    name: go@{{ go_version }}
  when: ansible_distribution == 'MacOSX' or ansible_distribution == 'Ubuntu'

- name: GOPATH is set on .zprofile
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.zprofile"
    line: export GOPATH=$HOME/go

- name: GOPATH is on PATH in .zprofile
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.zprofile"
    line: export PATH=$PATH:$GOPATH/bin