- name: Download Golang {{ go_version }}
  ansible.builtin.get_url:
    url: https://go.dev/dl/go{{ go_version }}.linux-amd64.tar.gz
    dest: /tmp/go{{ go_version }}.linux-amd64.tar.gz
    mode: u+rwx
  become: false

- name: Delete /usr/local/go
  ansible.builtin.file:
    path: /usr/local/go
    state: absent
  become: true

- name: Install go{{ go_version }} to /usr/local/go
  ansible.builtin.unarchive:
    src: /tmp/go{{ go_version }}.linux-amd64.tar.gz
    dest: /usr/local
  become: true

- name: Add /usr/local/go/bin to /etc/profile
  ansible.builtin.lineinfile:
    path: /etc/profile
    line: export PATH=$PATH:/usr/local/go/bin
  become: true

- name: Delete go{{ go_version }}.linux-amd64.tar.gz file
  ansible.builtin.file:
    path: /tmp/go{{ go_version }}.linux-amd64.tar.gz
    state: absent
  become: false