- name: Install Java OpenJDK {{ java_version }}
  community.general.homebrew:
    name: openjdk@{{ java_version }}
  when: ansible_distribution == 'MacOSX' or ansible_distribution == 'Ubuntu'

- name: Correct java version selected
  community.general.alternatives:
    name: java
    path: "{{ ansible_env.HOMEBREW_PREFIX }}/opt/openjdk@{{ java_version }}/bin/java"
  become: true
  when: ansible_distribution == 'Ubuntu'
