---

- name: Git Setup
  hosts: localhost

  vars_prompt:
   - name: "user_name"
     prompt: "Enter git username"
     private: no

   - name: "user_email"
     prompt: "Enter the email to use as your commit email address"
     private: no

  roles:
    - { role: git }