---

- name: Git Setup
  hosts: localhost

  vars_prompt:

    - name: user_email
      prompt: What is your git email?
      private: false

  vars:
    user_name: "{{ ansible_user_id }}"

  roles:
    - { role: git }
    - { role: ssh-key }