---
- name: Install nvm(node version manager) and use it to install Node.js
  hosts: 127.0.0.1
  connection: local

  vars:
    nodejs_version: 14.16.0
    nvm_version: v0.37.2

  tasks:
    - name: Download the nvm install script
      get_url: 
        url: https://raw.githubusercontent.com/nvm-sh/nvm/{{ nvm_version }}/install.sh 
        dest: /tmp
        mode: u+rwx
      become: false

    - name: Execute the nvm install script
      shell: 
        cmd: bash install.sh 
        chdir: /tmp 
        executable: /bin/bash
      become: false

    - name: Delete the nvm install script
      file:
        path: /tmp/install.sh
        state: absent
      become: false

    - name: Install Node.js {{ nodejs_version }}
      shell:
        cmd: . {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install {{ nodejs_version }}
      args:
        executable: /bin/bash
        chdir: "{{ ansible_env.HOME }}"
        creates: "{{ ansible_env.HOME }}/.nvm/versions/node/v{{ nodejs_version }}"
      become: false

    - name: Set Node.js {{ nodejs_version }} as the default
      shell:
        cmd: . {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm alias default {{ nodejs_version }}
      args:
        executable: /bin/bash
        chdir: "{{ ansible_env.HOME }}"
      become: false