---
- name: Install Vagrant and Virtualbox
  hosts: 127.0.0.1
  connection: local

  vars:
    nodejs_version: v14.16.0

  tasks:
    - name: Download Node.js {{ nodejs_version }}
      get_url:
        url: https://nodejs.org/dist/{{ nodejs_version }}/node-{{ nodejs_version }}-linux-x64.tar.xz
        dest: /tmp
        checksum: sha256:https://nodejs.org/dist/{{ nodejs_version }}/SHASUMS256.txt
      become: true

    - name: Create /usr/local/lib/nodejs 
      file:
        path: /usr/local/lib/nodejs
        state: directory
        mode: '0755'
      become: true

    - name: Untar Node.js archive to /usr/local/lib/nodejs
      unarchive:
        src: /tmp/node-{{ nodejs_version }}-linux-x64.tar.xz
        dest: /usr/local/lib/nodejs
      become: true

    - name: Delete Node.js tar file
      file:
        path: /tmp/node-{{ nodejs_version }}-linux-x64.tar.xz
        state: absent
      become: true



