---
- name: Install Node.js and configure for ansible user
  hosts: 127.0.0.1
  connection: local

  vars:
    nodejs_version: v14.16.0

  tasks:
    - name: Download Node.js {{ nodejs_version }}
      get_url:
        url: https://nodejs.org/dist/{{ nodejs_version }}/node-{{ nodejs_version }}-linux-x64.tar.xz
        dest: /tmp
        checksum: sha256:https://nodejs.org/dist/{{ nodejs_version }}/SHASUMS256.txt
      become: true

    - name: Create /usr/local/lib/nodejs 
      file:
        path: /usr/local/lib/nodejs
        state: directory
        mode: '0755'
      become: true

    - name: Untar Node.js archive to /usr/local/lib/nodejs
      unarchive:
        src: /tmp/node-{{ nodejs_version }}-linux-x64.tar.xz
        dest: /usr/local/lib/nodejs
      become: true

    - name: Delete Node.js tar file
      file:
        path: /tmp/node-{{ nodejs_version }}-linux-x64.tar.xz
        state: absent
      become: true

    - name: Add Node.js location to ansible user's PATH
      lineinfile:
        path: /home/{{ ansible_user }}/.profile
        line: "export PATH=/usr/local/lib/nodejs/node-{{ nodejs_version }}-linux-x64/bin:$PATH"
      become: false

    - name: Create npm global directory for ansible user to avoid permission issues with global installs
      file:
        path: /home/{{ ansible_user }}/.npm-global
        state: directory
        mode: '0755'
      become: false

    - name: Configure npm directory location
      shell:
        cmd: npm config set prefix '~/.npm-global'
      become: false

    - name: Add npm global directory to ansible user's PATH
      lineinfile:
        path: /home/{{ ansible_user }}/.profile
        line: "export PATH=~/.npm-global/bin:$PATH"
      become: false 
