---
- name: Setup and configure git
  hosts: 127.0.0.1
  connection: local

  vars_prompt:
   - name: "user_name"
     prompt: "Enter git username"
     private: no

   - name: "user_email"
     prompt: "Enter the email to use as your commit email address"
     private: no

  tasks:
    - name: Install git
      apt:
        name: git
        state: present
        update_cache: true
      become: true

    - name: Set user.name
      git_config:
        name: user.name
        value: "{{ user_name }}"
        scope: global
      become: false
    
    - name: Set user.email
      git_config:
        name: user.email
        value: "{{ user_email }}"
        scope: global
      become: false
