- name: Install protobuf (dependency) and protoc-gen-go-grpc Homebrew package
  community.general.homebrew:
    name: protoc-gen-go-grpc
  when: ansible_distribution == 'MacOSX' or ansible_distribution == 'Ubuntu'

- name: Install grpcio python modules
  ansible.builtin.pip:
    name: "{{ item }}"
  loop:
    - grpcio
    - grpcio-tools
  when: ansible_distribution == 'MacOSX' or ansible_distribution == 'Ubuntu'
