- name: Install protobuf (dependency) and protoc-gen-go-grpc Homebrew package
  community.general.homebrew:
    name: protoc-gen-go-grpc
  when: ansible_distribution == 'MacOSX' or ansible_distribution == 'Ubuntu'