- name: Install Ollama Homebrew package
  community.general.homebrew:
    name: ollama
  become: false
  when: ansible_distribution == 'MacOSX' or ansible_distribution == 'Ubuntu'

- name: Register Ollama as a service
  ansible.builtin.command: brew services start ollama
  become: false
  when: ansible_distribution == 'MacOSX' or ansible_distribution == 'Ubuntu'

- name: Pull Llama 3.2 model
  ansible.builtin.command: ollama pull llama3.2:latest
  become: false
  when: ansible_distribution == 'MacOSX' or ansible_distribution == 'Ubuntu'
