- name: Install Ollama Homebrew package
  community.general.homebrew:
    name: ollama
  become: false
  when: ansible_distribution == 'MacOSX' or ansible_distribution == 'Ubuntu'

- name: Register Ollama as a service
  ansible.builtin.command: brew services start ollama
  become: false
  when: ansible_distribution == 'MacOSX' or ansible_distribution == 'Ubuntu'

- name: Pull Code Llama-13b-Instruct model
  ansible.builtin.command: ollama pull codellama:13b-instruct
  become: false
  when: ansible_distribution == 'MacOSX' or ansible_distribution == 'Ubuntu'

- name: Pull Deepseek-Coder-6.7b-Instruct model
  ansible.builtin.command: ollama pull deepseek-coder:6.7b-instruct
  become: false
  when: ansible_distribution == 'MacOSX' or ansible_distribution == 'Ubuntu'

- name: Pull Llama 3 Instruct model
  ansible.builtin.command: ollama pull llama3:instruct
  become: false
  when: ansible_distribution == 'MacOSX' or ansible_distribution == 'Ubuntu'

- name: Pull Mixtral Instruct model
  ansible.builtin.command: ollama pull mixtral:instruct
  become: false
  when: ansible_distribution == 'MacOSX' or ansible_distribution == 'Ubuntu'

